alert ("Welcome to Agar.io");
alert ("Happy New Year 2016!");
alert;
var alert = ['NO HACKING'];
array;
control = ['Follow'];
array = ['controlblob'];
controlblob = [StopHacker];
StopHacker = ['banhacker'];
Java = 'nodejs';
